apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: greenlogistics-alertmanager-config
  namespace: monitoring
  labels:
    release: kps
    team: greenlogistics
    env: dev
spec:
  route:
    groupBy: ['alertname']
    groupWait: 10s
    groupInterval: 1m
    repeatInterval: 10m
    receiver: 'mailhog'
  receivers:
    - name: 'mailhog'
      emailConfigs:
        - to: 'team@greenlogistics.local'
          from: 'alerts@greenlogistics.local'
          smarthost: 'mailhog.mail.svc.cluster.local:1025'
          requireTLS: false
          sendResolved: true
